const API='http://localhost:5000/api';
const demoCourses=[{id:'python',title:'Python Programming',icon:'🐍',level:'Beginner',lessons:[{id:'p1',title:'Lesson 1: Python Introduction',video:'https://www.youtube.com/embed/dQw4w9WgXcQ',slides:'#',description:'Understand Python, installation and your first program.'},{id:'p2',title:'Lesson 2: Variables and Data Types',video:'https://www.youtube.com/embed/dQw4w9WgXcQ',slides:'#',description:'Learn variables, strings, numbers and booleans.'},{id:'p3',title:'Lesson 3: Conditions and Loops',video:'https://www.youtube.com/embed/dQw4w9WgXcQ',slides:'#',description:'Build logic with if statements and loops.'}]},{id:'web',title:'Modern Web Development',icon:'🌐',level:'Beginner',lessons:[]},{id:'games',title:'Python Game Development',icon:'🎮',level:'Intermediate',lessons:[]}];
let state={page:'home',user:null,courses:demoCourses,course:null,lesson:null,auth:'login',message:''};
const app=document.getElementById('app');
function nav(){return `<header class="top"><nav class="nav"><button class="ghost brand" onclick="go('home')">Codewith<b>Hafiz</b></button><div class="navlinks"><button onclick="go('home')">Home</button><button onclick="go('courses')">Courses</button><button onclick="go('tutorials')">Tutorials</button><button onclick="go('about')">About</button></div><div class="navactions">${state.user?`<button class="outline" onclick="go('dashboard')">Dashboard</button><button class="primary" onclick="logout()">Logout</button>`:`<button class="outline" onclick="openAuth('login')">Sign in</button><button class="primary" onclick="openAuth('signup')">Create account</button>`}</div><button class="menu" onclick="go('courses')">☰</button></nav></header>`}
function home(){return `<section class="hero"><div class="hero-inner"><div><div class="eyebrow">Learn without limits</div><h1>Build skills that<br><span>build your future.</span></h1><p>Master Python, web development and practical coding through structured lessons, projects and practice material. Everything is free.</p><div class="hero-buttons"><button class="primary" onclick="go('courses')">Explore courses →</button><button class="outline" onclick="go('tutorials')">View tutorials</button></div></div><div class="hero-card"><div class="mini-top"><strong>Learning dashboard</strong><span class="pill">FREE</span></div><p class="small">Your weekly learning progress</p><div class="progress"><i style="width:68%"></i></div><div class="statgrid"><div class="stat"><strong>12</strong><span class="small">Lessons</span></div><div class="stat"><strong>08</strong><span class="small">Projects</span></div><div class="stat"><strong>100%</strong><span class="small">Free</span></div></div><div class="notice">✓ Practice slides included with lessons</div></div></div></section><section class="section setup-section"><div class="section-head"><div><h2>Start coding in 3 steps</h2><p>Download the essential tools directly from their official sources.</p></div></div><div class="setup-grid"><article class="setup-card"><div class="setup-icon">🐍</div><h3>Download Python</h3><p>Install Python for running programs and projects.</p><a class="primary setup-link" href="https://www.python.org/downloads/windows/" target="_blank" rel="noopener">Download Python ↗</a></article><article class="setup-card"><div class="setup-icon">💻</div><h3>Download VS Code</h3><p>Install the code editor used in our lessons.</p><a class="primary setup-link" href="https://code.visualstudio.com/download" target="_blank" rel="noopener">Download VS Code ↗</a></article><article class="setup-card"><div class="setup-icon">🧩</div><h3>Python Extension</h3><p>Open the official Microsoft Python extension page.</p><a class="primary setup-link" href="https://marketplace.visualstudio.com/items?itemName=ms-python.python" target="_blank" rel="noopener">Get Extension ↗</a></article></div></section><section class="section"><div class="section-head"><div><h2>Start learning today</h2><p>Carefully designed courses for real progress.</p></div><button class="ghost" onclick="go('courses')">See all courses →</button></div>${courseCards(demoCourses)}</section><footer class="footer">© 2026 CodewithHafiz · Learn. Build. Grow.</footer>`}
function courseCards(list){return `<div class="cards">${list.map(c=>`<article class="course"><div class="course-cover">${c.icon}</div><div class="course-body"><h3>${c.title}</h3><p>Structured lessons, practical examples and downloadable practice material.</p><div class="meta"><span>${c.level}</span><span>${c.lessons.length||8} lessons</span></div><button class="primary" onclick="openCourse('${c.id}')">View course</button></div></article>`).join('')}</div>`}
function courses(){return `<main class="page"><div class="section-head"><div><h2>Explore free courses</h2><p>Learn at your own pace with guided lessons.</p></div><input class="search" placeholder="Search courses..." oninput="filterCourses(this.value)"></div><div id="course-list">${courseCards(state.courses)}</div></main><footer class="footer">All courses on CodewithHafiz are free.</footer>`}
function tutorials(){return `<main class="page"><h2>Latest tutorials</h2><p class="small">Short, practical guides to help you code better.</p><div class="cards" style="margin-top:25px"><article class="course"><div class="course-cover">💻</div><div class="course-body"><h3>Build your first website</h3><p>Learn the basic structure of a modern website.</p><button class="primary" onclick="openAuth('signup')">Start learning</button></div></article><article class="course"><div class="course-cover">🐍</div><div class="course-body"><h3>Python beginner tips</h3><p>Understand the concepts every new Python learner needs.</p><button class="primary" onclick="openCourse('python')">Read tutorial</button></div></article></div></main>`}
function auth(){return `<main class="page"><div class="auth"><h2>${state.auth==='login'?'Welcome back':'Create your free account'}</h2><p class="small">${state.auth==='login'?'Sign in to continue learning.':'Join CodewithHafiz and start learning for free.'}</p>${state.message?`<div class="notice ${state.message.includes('wrong')||state.message.includes('required')?'error':''}">${state.message}</div>`:''}<div class="field"><label>${state.auth==='signup'?'Full name':'Email address'}</label>${state.auth==='signup'?'<input id="name" placeholder="Your name">':''}<input id="email" type="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="Enter password"></div>${state.auth==='signup'?'<div class="field"><label>Confirm password</label><input id="confirm" type="password" placeholder="Repeat password"></div>':''}<button class="primary" style="width:100%" onclick="submitAuth()">${state.auth==='login'?'Sign in':'Create account'}</button><p class="small" style="margin-top:20px">${state.auth==='login'?`New here? <button class="ghost" onclick="openAuth('signup')">Create an account</button>`:`Already have an account? <button class="ghost" onclick="openAuth('login')">Sign in</button>`}</p><p class="small">Demo student: student@example.com / student123</p></div></main>`}
function coursePage(){let c=state.course;let l=state.lesson||c.lessons[0];return `<main class="page"><button class="ghost" onclick="go('courses')">← Back to courses</button><h1 style="margin-bottom:8px">${c.icon} ${c.title}</h1><p class="small">Free structured course · Watch lessons and open practice slides separately.</p><div class="lesson-layout" style="margin-top:25px"><aside class="sidebar"><h3>Course lessons</h3>${(c.lessons.length?c.lessons:[{id:'x',title:'Lessons coming soon'}]).map(x=>`<button class="lesson-btn ${l&&x.id===l.id?'active':''}" onclick="selectLesson('${x.id}')">${x.title}</button>`).join('')}</aside><section class="contentbox">${l&&l.id!=='x'?`<h2>${l.title}</h2><p>${l.description}</p><div class="video">▶</div><h3>Practice material</h3><div class="material"><strong>📑 Practice slides for this lesson</strong><p class="small">Open the separate slides after watching the video.</p><button class="outline" onclick="openSlides('${l.slides}')">Open practice slides →</button></div>`:'<div class="notice">This course is being prepared. Check back soon.</div>'}</section></div></main>`}
function dashboard(){return `<main class="page"><h1>Student dashboard</h1><p class="small">Welcome back, ${state.user?.name||'Student'}.</p><div class="dashgrid" style="margin-top:25px"><div class="dashcard"><span class="small">Enrolled courses</span><strong>1</strong></div><div class="dashcard"><span class="small">Completed lessons</span><strong>0</strong></div><div class="dashcard"><span class="small">Learning status</span><strong style="font-size:20px;color:var(--green)">Active</strong></div></div><div class="contentbox" style="margin-top:25px"><h2>Continue learning</h2><p>Python Programming</p><button class="primary" onclick="openCourse('python')">Continue course →</button></div></main>`}
function about(){return `<main class="page"><h1>About CodewithHafiz</h1><p style="max-width:700px;line-height:1.8;color:var(--muted)">CodewithHafiz is a free learning platform focused on practical programming education. Our goal is to make quality coding lessons, practice slides and projects accessible to everyone.</p></main>`}
function render(){app.innerHTML=nav()+(state.page==='home'?home():state.page==='courses'?courses():state.page==='tutorials'?tutorials():state.page==='auth'?auth():state.page==='course'?coursePage():state.page==='dashboard'?dashboard():about())}
function go(p){state.page=p;state.message='';render()}
function openAuth(type){state.auth=type;state.page='auth';state.message='';render()}
function submitAuth(){let email=document.getElementById('email').value.trim(),pass=document.getElementById('password').value; if(!email||!pass){state.message='Email and password are required.';return render()}if(state.auth==='signup'){let name=document.getElementById('name').value.trim(),confirm=document.getElementById('confirm').value;if(!name||pass!==confirm){state.message='Please fill all fields and make sure passwords match.';return render()}state.user={name,email};state.page='dashboard';return render()}if(email==='student@example.com'&&pass==='student123'||email==='admin@codewithhafiz.com'&&pass==='Hafiz@123'){state.user={name:email.startsWith('admin')?'Admin':'Student',email};state.page='dashboard';render()}else{state.message='wrong login details. Use the demo credentials shown below.';render()}}
function logout(){state.user=null;go('home')}
function openCourse(id){state.course=state.courses.find(x=>x.id===id)||demoCourses[0];state.lesson=state.course.lessons[0];state.page='course';render()}
function selectLesson(id){state.lesson=state.course.lessons.find(x=>x.id===id);render()}
function openSlides(url){if(url&&url!=='#')window.open(url,'_blank');else alert('Practice slides link is not added yet. Admin can add a PDF or slide link for this lesson.')}
function filterCourses(q){let x=state.courses.filter(c=>c.title.toLowerCase().includes(q.toLowerCase()));document.getElementById('course-list').innerHTML=courseCards(x)}
render();
